Repository schubergphilis/terraform-aws-mcaf-account-baseline, pull requests merged in 2024-01, with the labels that each got.

#16 bug: modify service quotas manager role name
  README.md
  examples/basic/.gitkeep
  examples/basic/main.tf
  examples/basic/versions.tf
  main.tf
Labels: bug

#15 breaking: Control Tower 3.0 support
  README.md
  data.tf
  locals.tf
  main.tf
  variables.tf
Labels: breaking

#17 docs: improve service quotas manager documentation
  README.md
Labels: documentation
